---
name: "tiller"
version: "0.3.1"
usage: "Please see https://github.com/rimusz/helm-tiller for usage"
description: "(Q Fork) Start a Tiller server locally"
command: "$HELM_PLUGIN_DIR/scripts/tiller.sh"
useTunnel: false
